theme: jekyll-theme-minimal
title: Home of uksmit
description: GitHub Pages sandbox

header_navigation:
  - title: About
    url: /about/
  - title: Blog
    url: /blog/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Sean M"
  - scope:
      path: ""
    values:
      layout: "default"
